# Generated by Django 4.2.2 on 2024-06-04 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0006_remove_componentstorage_owner_and_more'),
        ('hardware', '0012_delete_componentrepairmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolE2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('file_1', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ВГ на АРВ1')),
                ('file_2', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ВГ на АРВ2')),
                ('file_3', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса гашения ТП ВГ на АРВ1')),
                ('file_4', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса гашения ТП ВГ на АРВ2')),
                ('file_5', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1')),
                ('file_6', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2')),
                ('file_7', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1')),
                ('file_8', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2')),
                ('file_9', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса гашения ГГ на АРВ1')),
                ('file_10', models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса гашения ГГ на АРВ2')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_e2', to='hardware.connection', verbose_name='Присоединение')),
                ('instruments', models.ManyToManyField(related_name='protocol_e2', to='warehouse.instrument', verbose_name='Инструменты')),
                ('signers', models.ManyToManyField(related_name='protocol_e2', to=settings.AUTH_USER_MODEL, verbose_name='Подписывающие')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Протокол Э2',
                'verbose_name_plural': 'Протоколы Э2',
                'ordering': ('date',),
            },
        ),
        migrations.AddConstraint(
            model_name='protocole2',
            constraint=models.UniqueConstraint(fields=('date', 'connection'), name='date_connection_uniquetogether'),
        ),
    ]
