# Generated by Django 4.2.2 on 2024-06-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocole2',
            name='file_5',
            field=models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1 в режиме (Ug)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_6',
            field=models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2 в режиме (Ug)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_7',
            field=models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1 в режиме (If)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_8',
            field=models.FileField(upload_to='protocols/e2/', verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2 в режиме (If)'),
        ),
    ]
