# Generated by Django 4.2.2 on 2024-07-09 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_protocole2_file_5_alter_protocole2_file_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocole2',
            name='file_1',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ВГ на АРВ1'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_10',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса гашения ГГ на АРВ2'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_2',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ВГ на АРВ2'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_3',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса гашения ТП ВГ на АРВ1'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_4',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса гашения ТП ВГ на АРВ2'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_5',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1 в режиме (Ug)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_6',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2 в режиме (Ug)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_7',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ1 в режиме (If)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_8',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса возбуждения ГГ на АРВ2 в режиме (If)'),
        ),
        migrations.AlterField(
            model_name='protocole2',
            name='file_9',
            field=models.FileField(upload_to='protocols/e2/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Осциллограмма процесса гашения ГГ на АРВ1'),
        ),
    ]
