# Generated by Django 5.1.1 on 2024-09-28 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_protocole2_file_1_alter_protocole2_file_10_and_more'),
        ('hardware', '0014_alter_part_comment'),
        ('warehouse', '0008_instrument_type_alter_instrument_verification_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='docs/protocols/templates/', validators=[django.core.validators.FileExtensionValidator(('html',))], verbose_name='HTML-шаблон')),
            ],
            options={
                'verbose_name': 'Шаблон протокола',
                'verbose_name_plural': 'Шаблоны протоколов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='hardware.connection', verbose_name='Присоединение')),
                ('instruments', models.ManyToManyField(blank=True, related_name='protocols', to='warehouse.instrument', verbose_name='Инструменты')),
                ('signers', models.ManyToManyField(related_name='protocols', to=settings.AUTH_USER_MODEL, verbose_name='Подписывающие')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Протокол ТО',
                'verbose_name_plural': 'Протоколы ТО',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Наименование элемента')),
                ('value', models.FileField(upload_to='docs/protocols/files', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'csv'))], verbose_name='Файл')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'constraints': [models.UniqueConstraint(fields=('slug', 'protocol'), name='file_slug_protocol_uniquetogether')],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Наименование элемента')),
                ('value', models.TextField(verbose_name='Текст')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'constraints': [models.UniqueConstraint(fields=('slug', 'protocol'), name='text_slug_protocol_uniquetogether')],
            },
        ),
    ]
