# Generated by Django 5.1.1 on 2024-10-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_template_protocol_file_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtocolE2',
        ),
    ]
