# Generated by Django 5.1.1 on 2024-10-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_delete_protocole2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Float',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Наименование элемента')),
                ('value', models.FloatField(verbose_name='Вещественное число')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Вещественное число',
                'verbose_name_plural': 'Вещественные числа',
                'constraints': [models.UniqueConstraint(fields=('slug', 'protocol'), name='float_slug_protocol_uniquetogether')],
            },
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Наименование элемента')),
                ('value', models.IntegerField(verbose_name='Целое число')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Целое число',
                'verbose_name_plural': 'Целые числа',
                'constraints': [models.UniqueConstraint(fields=('slug', 'protocol'), name='integer_slug_protocol_uniquetogether')],
            },
        ),
    ]
