# Generated by Django 5.1.1 on 2024-10-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_float_integer'),
        ('hardware', '0014_alter_part_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='hardware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='hardware.hardware', verbose_name='Оборудование'),
        ),
    ]
