# Generated by Django 5.1.1 on 2024-10-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_protocol_hardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='connection',
        ),
    ]
