version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: planner_db
    restart: always
    volumes:
      - planner_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  adminer:
    image: adminer
    container_name: planner_adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  backend:
    build: .
    container_name: planner_backend
    restart: always
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_value:/resource_planner/static/
      - media_value:/resource_planner/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: planner_nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
  certbot:
    image: certbot/certbot
    container_name: planner_certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  planner_db:
  static_value:
  media_value:
