version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: planner_db
    restart: always
    volumes:
      - planner_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  adminer:
    image: adminer
    container_name: planner_adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  backend:
    build: .
    container_name: planner_backend
    restart: always
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_value:/resource_planner/static/
      - media_value:/resource_planner/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: planner_nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  planner_db:
  static_value:
  media_value:
