# Generated by Django 4.0.1 on 2022-01-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0001_initial'),
        ('warehouse', '0003_material_delete_materials_alter_instrument_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='repairs.object', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Ресурсная ведомость',
                'verbose_name_plural': 'Ресурсные ведомости',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OperationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repairs.operation')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='resources.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='resources.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.instrument')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='resources.sheet')),
            ],
        ),
    ]
