# Generated by Django 4.0.1 on 2022-01-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={'ordering': ('name',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
