# Generated by Django 4.1 on 2022-08-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("defects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="defects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник обнаруживший дефект",
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="features",
            field=models.ManyToManyField(
                related_name="defects",
                to="defects.feature",
                verbose_name="Признаки дефекта",
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="hardware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defects",
                to="hardware.hardware",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="organizational_reasons",
            field=models.ManyToManyField(
                blank=True,
                related_name="defects",
                to="defects.organizationalreason",
                verbose_name="Организационные причины",
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="technical_reasons",
            field=models.ManyToManyField(
                blank=True,
                related_name="defects",
                to="defects.technicalreason",
                verbose_name="Технические причины дефекта",
            ),
        ),
    ]
