# Generated by Django 4.0.6 on 2022-08-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='dispatch_object',
        ),
    ]
