# Generated by Django 4.1 on 2022-12-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='defects/attachments/%Y/%m/%d/', verbose_name='Приложение'),
        ),
    ]
