# Generated by Django 4.1 on 2022-10-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='hardware',
        ),
    ]
