# Generated by Django 4.0.6 on 2022-08-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_component_cabinet'),
        ('defects', '0002_remove_defect_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('is_dependent', models.BooleanField(default=False, verbose_name='Зависит от внешних условий')),
            ],
            options={
                'verbose_name': 'Организационная причина',
                'verbose_name_plural': 'Организационные причины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TechnicalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('is_dependent', models.BooleanField(default=False, verbose_name='Зависит от внешних условий')),
            ],
            options={
                'verbose_name': 'Техническая причина',
                'verbose_name_plural': 'Технические причины',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='condition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='slug',
        ),
        migrations.AddField(
            model_name='defect',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='hardware.cabinet', verbose_name='Шкаф/панель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='hardware.component', verbose_name='Комплектующее'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='organizational_reasons',
            field=models.ManyToManyField(blank=True, related_name='defects', to='defects.organizationalreason', verbose_name='Организационные причины'),
        ),
        migrations.AddField(
            model_name='defect',
            name='technical_reasons',
            field=models.ManyToManyField(blank=True, related_name='defects', to='defects.technicalreason', verbose_name='Технические причины дефекта'),
        ),
    ]
