# Generated by Django 4.1 on 2023-05-11 12:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_defect_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[1280, 720], upload_to='defects/images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
