# Generated by Django 4.2.1 on 2023-05-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_part_part_name_cabinet_uniquetogether'),
        ('defects', '0003_alter_defect_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='component',
        ),
        migrations.AddField(
            model_name='defect',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='hardware.part', verbose_name='Комплектующее'),
        ),
    ]
