# Generated by Django 4.1 on 2022-08-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('abbreviation', models.CharField(max_length=30, unique=True, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Группа оборудования',
                'verbose_name_plural': 'Группы оборудования',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='hardware',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='hardware.connection', verbose_name='Присоединение'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='hardware.group', verbose_name='Группа оборудования'),
        ),
    ]
