# Generated by Django 4.1 on 2023-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_group_alter_hardware_connection_hardware_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='abbreviation',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='inventory_number',
            field=models.CharField(max_length=50, verbose_name='Инв. номер'),
        ),
    ]
