# Generated by Django 4.0.6 on 2022-08-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_cabinet_component_design_repairmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назначение комплектующего')),
            ],
            options={
                'verbose_name': 'Назначение комплектующего',
                'verbose_name_plural': 'Назначения комплектующих',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='Design',
            new_name='ComponentDesign',
        ),
        migrations.RenameModel(
            old_name='RepairMethod',
            new_name='ComponentRepairMethod',
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('facility', 'abbreviation'), 'verbose_name': 'Присоединение', 'verbose_name_plural': 'Присоединения'},
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'facility'), name='abbreviation_facility_uniquetogether'),
        ),
        migrations.AlterField(
            model_name='component',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='hardware.componentfunction', verbose_name='Назначение'),
        ),
    ]
