# Generated by Django 4.0.6 on 2022-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_componentfunction_rename_design_componentdesign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdesign',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True, verbose_name='Аббревиатура'),
        ),
    ]
