# Generated by Django 4.2.1 on 2023-05-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_remove_cabinet_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Изготовитель оборудования',
                'verbose_name_plural': 'Изготовители оборудования',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='hardware.manufacturer', verbose_name='Изготовитель'),
        ),
    ]
