# Generated by Django 4.0.6 on 2022-08-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_componentdesign_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hardware.cabinet', verbose_name='Шкаф/Панель'),
        ),
    ]
