# Generated by Django 4.1 on 2022-08-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_component_cabinet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ('hardware', 'abbreviation'), 'verbose_name': 'Шкаф/панель', 'verbose_name_plural': 'Шкафы/панели'},
        ),
        migrations.RemoveConstraint(
            model_name='cabinet',
            name='operational_name_hardware_uniquetogether',
        ),
        migrations.RenameField(
            model_name='cabinet',
            old_name='operational_name',
            new_name='abbreviation',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware', to='hardware.connection', verbose_name='Присоединение'),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('abbreviation', 'hardware'), name='abbreviation_hardware_uniquetogether'),
        ),
    ]
