# Generated by Django 4.2.1 on 2023-05-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_manufacturer_cabinet_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name',), 'verbose_name': 'Компонент / запчасть', 'verbose_name_plural': 'Компоненты / запчасти'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='component',
            name='component',
        ),
        migrations.RemoveField(
            model_name='component',
            name='launch_year',
        ),
        migrations.RemoveField(
            model_name='component',
            name='release_year',
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='hardware.manufacturer', verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='hardware.manufacturer', verbose_name='Изготовитель'),
        ),
    ]
