# Generated by Django 4.2.1 on 2023-05-17 02:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_alter_component_options_remove_component_cabinet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Условное обозначение')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1972), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска')),
                ('launch_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1972), django.core.validators.MaxValueValidator(2050)], verbose_name='Год ввода в эксплуатацию')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hardware.cabinet', verbose_name='Шкаф/Панель')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='hardware.component', verbose_name='Компонент')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='hardware.part', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Комплектующее / Деталь',
                'verbose_name_plural': 'Комплектующие / Детали',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name', 'cabinet'), name='name_cabinet_uniquetogether'),
        ),
    ]
