# Generated by Django 4.2.1 on 2023-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_alter_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer', 'type'), name='name_manufacturer_type_uniquetogether'),
        ),
    ]
