# Generated by Django 4.2.1 on 2023-09-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_alter_component_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentdesign',
            options={'ordering': ('abbreviation',), 'verbose_name': 'Вариант исполнения', 'verbose_name_plural': 'Варианты исполнения'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='repair_method',
        ),
    ]
