# Generated by Django 4.2.1 on 2023-09-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_alter_componentdesign_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentRepairMethod',
        ),
    ]
