# Generated by Django 4.2.2 on 2024-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_delete_componentrepairmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
