# Generated by Django 4.2.2 on 2024-08-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_part_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
