# Generated by Django 4.2.1 on 2023-08-23 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
