# Generated by Django 4.0.1 on 2022-01-09 16:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('inventory_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инв. номер')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зав. номер')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='materials/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='materials',
            name='turnover',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во применений'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='measurement_unit',
            field=models.CharField(max_length=20, verbose_name='Единица измерения'),
        ),
    ]
