# Generated by Django 4.0.1 on 2022-01-11 13:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_instrument_materials_turnover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('measurement_unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('inventory_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инв. номер')),
                ('article_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Артикул')),
                ('turnover', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во применений')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='material/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='instrument/', verbose_name='Изображение'),
        ),
    ]
