# Generated by Django 4.2.1 on 2023-08-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('warehouse', '0002_alter_materialstorage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='warehouse.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='materialstorage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='staff.dept', verbose_name='Подразделение'),
        ),
    ]
