# Generated by Django 4.0.1 on 2022-01-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_material_delete_materials_alter_instrument_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('name',), 'verbose_name': 'Инструмент/Прибор', 'verbose_name_plural': 'Инструменты/Приборы'},
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('parent_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='warehouse.storage', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='warehouse.storage', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='material',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='warehouse.storage', verbose_name='Место хранения'),
        ),
    ]
