# Generated by Django 4.2.1 on 2024-01-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_storage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentstorage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialstorage',
            name='owner',
        ),
    ]
