# Generated by Django 4.0.1 on 2022-01-14 18:14

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_dept_abbreviation'),
        ('warehouse', '0005_alter_instrument_options_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Список материалов', 'verbose_name_plural': 'Список материалов'},
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='material',
            name='inventory_number',
        ),
        migrations.RemoveField(
            model_name='material',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='material',
            name='turnover',
        ),
        migrations.AddField(
            model_name='instrument',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='staff.dept', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='material/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='MaterialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инв. номер')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amount', to='warehouse.material', verbose_name='Материал')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='staff.dept', verbose_name='Подразделение')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='warehouse.storage', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Материал на хранении',
                'verbose_name_plural': 'Материалы на хранении',
                'ordering': ('material',),
            },
        ),
    ]
