# Generated by Django 4.2.2 on 2024-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_instrument_last_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='verification_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Период проверки (месяцев)'),
        ),
    ]
