# Generated by Django 4.0.1 on 2022-01-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_dept_abbreviation'),
        ('warehouse', '0007_alter_instrument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse/qr/', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='staff.dept', verbose_name='Подразделение'),
        ),
    ]
