# Generated by Django 4.0.1 on 2022-01-16 08:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_storage_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='instrument/', verbose_name='Изображение'),
        ),
    ]
