# Generated by Django 4.0.3 on 2022-03-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_instrument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='warehouse.storage', verbose_name='Место хранения'),
        ),
    ]
