# Generated by Django 4.0.3 on 2022-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_materialstorage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
