# Generated by Django 4.0.3 on 2022-03-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_dept_abbreviation'),
        ('warehouse', '0013_alter_materialstorage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='staff.dept', verbose_name='Подразделение'),
        ),
    ]
